### ISSUE TITLE
Licensing header issue

### ISSUE THREAD

**Issue by fbouliane** [internap/netman#115]
The per-file header license is hard to keep up-to-date and pollutes diff. The license's year of modification should not be a burden. The exact timestamp and author of modification is tracked using git anyway.
I think we should remove those License headers in our open-source project. 

Is there anyone against the removal of those headers ?

## Interesting talks on the subject :

* [Apache 2.0 license says](http://www.apache.org/dev/apply-license.html#new) we SHOULD (not MUST) add the license headers.
* [Openstack concedes](https://wiki.openstack.org/wiki/Documentation/Copyright) it's not needed.
* [Get Rid of Source Code Templates](http://hackerboss.com/get-rid-of-templates/).

**Comment by idjaw** [comment]
:+1:

**Comment by mat128** [comment]
I agree it's currently a pain. I suggest the following:
- Keep the main "LICENSE" file
- Keep adding license information to new files
- Stop modifying any date after initial commit of a file.

Decider?

**Comment by lindycoder** [comment]
I agree once a license is added it should'nt be modified and new license should bear the current year, not a span since the start of the project

:+1: for @mat128

**Comment by idjaw** [comment]
:+1:  Completely agree.

**Comment by fbouliane** [comment]
:+1:

**Comment by emmurd** [comment]
I agree too :+1:

**Comment by godp1301** [comment]
:+1:
