### ISSUE TITLE
Lock should be acquired before connecting

### ISSUE THREAD

**Issue by lindycoder** [internap/netman#49]
actually the connect to the switch is made before acquiring the lock, this means if 10 sessions opens on a switch with max 5 connections, even though we have a lock, we'll fail.

This mecanism has to be rethought

**Comment by lindycoder** [comment]
the connect and the start transaction should both do the connection

The connect : Use for non transactional calls, will not acquire a lock

Start transaction : Should obtain lock before connecting and commit/rollback at the end

**Comment by mat128** [comment]
Isn't that solved now with the new FlowControlSwitch?

**Comment by lindycoder** [comment]
Yes you are right
